export const cloudList = [
    // html5,
    'JavaScript',
    'CSS3',
    'HTML5',
    'SASS',
    'MongoDB',
    'ReactJS',
    'MySQL',
    'ExpressJS',
    'git',
    'Redux',
    'NodeJS',
    'authentication',
    'Mocha',
    'GraphQL',
    'jsonwebtoken',
    'Mongoose',
    'multer',
    'Material UI',
    'WebPack',
    'S3',
    'Firebase',
    'Accessibily',
    'REST API',
    'GitHub',
    'cookies',
    'AWS',
    'Route 53',
    'CloudFront',
    'Stripe',
    'Axios',
    'Enzyme',
    'hooks',
    'Context API',
    'sessions',
    'prop-types',
    'CORS',
    'Font Awesome',
    'Sqlite',
    'DENO',
    'NextJS',
    'TypeScript',
    'localStorage',
    'MVC',
    'Webflow',
    'JSON',
    'YAML',
    'GitHub Actions',
    'EC2',
    'NGINX',
    'SSL',
    'GPG',
    'Google Oauth2',
    'Nodemailer',
    'Solidity',
    'Hardhat',
    'Ethers',
    'OpenZeppelin',
    'Framer-motion'
  ];